[package]
name = "xobox"
version = "0.1.0"
authors = ["Santiago M. Mola <santi@mola.io>"]
edition = "2021"

[dependencies]
bstr = "0.2.17"

[dev-dependencies]
duct = "0.13.5"
pretty_assertions = "1.1.0"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
