[package]
name = "xobox"
version = "0.1.0"
authors = ["Santiago M. Mola <santi@mola.io>"]
edition = "2018"

[dependencies]

[dev-dependencies]
duct = "0.13.5"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
