name: ci
on: [push, pull_request]
env:
  RUST_BACKTRACE: 1
jobs:
  lint-fmt:
    name: lint (rustfmt)
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: format
        run: cargo fmt --all --check
  lint-clippy:
    name: lint (clippy)
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: clippy
        run: cargo clippy -- -F clippy::pedantic -F clippy::all
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: run tests
        run: cargo test
  test-coverage:
    name: test with coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:latest
      options: --security-opt seccomp=unconfined
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: run tests with coverage
        run: cargo tarpaulin --all-features --follow-exec --out Xml
      - name: upload to covdecov.io
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
